apiVersion: v1
kind: Service
metadata:
  name: pdbauto
  namespace: sample-app-namespace-1790789531404
  labels:
    app.kubernetes.io/name: pdbauto
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pdbauto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080